# Generated by Django 5.1.6 on 2025-02-22 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('regular_meeting_time', models.CharField(max_length=255)),
                ('location_of_reg_meeting_time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateTimeField(verbose_name='date and time of event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cune_connect.organization')),
            ],
        ),
    ]
